spring:
  application:
    name: service1
eureka:
  client:
    serviceUrl:
    #  defaultZone: http://admin:123@localhost:8081/eureka/
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8085
