spring:
  application:
    name: service1
eureka:
  client:
    serviceUrl:
     # defaultZone: http://eureka1:8081/eureka/,http://eureka2:8761/eureka/
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8082





redis:
  database: 0 # Redis数据库索引（默认为0）
  host: 127.0.0.1  #Redis服务器地址
  port: 6379 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  pool:
    max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 10 # 连接池中的最大空闲连接
    max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    min-idle: 5 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
